# Default values for myapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: docker-image-repo
  pullPolicy: Always  # Updated pull policy to always pull the latest image.

  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.16.0"

service:
  type: NodePort
  port: 8080
