server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: arpan-mondal
    password: Arpan@****
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
